# Generated by Django 3.2.4 on 2021-06-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Csv',
        ),
    ]
